### ISSUE TITLE
python 3 was not found

### ISSUE THREAD

**Issue by Ruchitha0716** [VaibhavSaini19/Crop-Yield-Prediction-using-ML#12]
![Screenshot 2022-06-21 154323](https://user-images.githubusercontent.com/97648555/174775906-c8e03ac1-53ae-4ddc-b37f-bf46718efdea.png)
Could you plz help me to solve this. Python has already  installed but it is showing python 3 was not found

**Comment by VaibhavSaini19** [comment]
Please install Python 3.x and ensure it binary path is present in system environment variable.

Closing this as this is not a project related issue
