### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by JB254** [VaibhavSaini19/Crop-Yield-Prediction-using-ML#2]
Please share your original model/notebook. Would like to see the algorithms used.

**Comment by VaibhavSaini19** [comment]
Hi
I've uploaded the model training and preprocessing files. 
There was a lot of trial and error going on at that time, so the code might be a bit clumsy.
Feel free to improve by contributing

**Comment by JB254** [comment]
OKay, will do. Thank you.

**Comment by VaibhavSaini19** [comment]
Wait, I just realised they were for another ml project. Will upload the correct ones soon, if I find them

**Comment by VaibhavSaini19** [comment]
I can't seem to find the original training file. 
The model used was a Random Forest model, if this helps

**Comment by JB254** [comment]
Is there really no way you can trace the original model? Would've loved to
see how you incorporated said Random Forest model

**Comment by VaibhavSaini19** [comment]
> Is there really no way you can trace the original model?

Unfortunately, I can't

**Comment by VaibhavSaini19** [comment]
Closing this now
