### ISSUE TITLE
Issue on prediction

### ISSUE THREAD

**Issue by Sathiyanarayanan-M** [VaibhavSaini19/Crop-Yield-Prediction-using-ML#3]
The prediction is not working properly it returns an error in predict.php
BTW good work
![git_crop_issue](https://user-images.githubusercontent.com/61767157/108491084-77de9180-72c9-11eb-9557-1e02354407da.PNG)

**Comment by VaibhavSaini19** [comment]
Hi @Sathiyanarayanan-M 
The `&1", $output, $error);` should not even appear in the output, as it it is commented. 
Can you please check if you accidentally uncommented that line?

Also, could you please specify your system specs, in case if this doesn't fix the issue
