### ISSUE TITLE
Issue with the prediction calculator

### ISSUE THREAD

**Issue by ayushrajsingh** [VaibhavSaini19/Crop-Yield-Prediction-using-ML#4]
Hi! I cloned your repository and then placed it in the htdocs folder of XAMPP. After that I edited and replaced YOUR_API_KEY with the one I subscribed. But now it shows this error.
Please help me out.
![Error](https://user-images.githubusercontent.com/48799387/111142701-fc5fbf80-85aa-11eb-8224-675bae35c123.jpeg)

**Comment by VaibhavSaini19** [comment]
@ayushrajsingh you don't have Python installed in your system.

Closing this as this isn't an valid issue in the project
