### ISSUE TITLE
Erroe

### ISSUE THREAD

**Issue by sbanon1306** [VaibhavSaini19/Crop-Yield-Prediction-using-ML#5]
C:\Users\bhapk\Downloads\Crop-Yield-Prediction-using-ML-master\venv\Scripts\python.exe C:/Users/bhapk/Downloads/Crop-Yield-Prediction-using-ML-master/RF_predict.py
Traceback (most recent call last):
  File "C:/Users/bhapk/Downloads/Crop-Yield-Prediction-using-ML-master/RF_predict.py", line 12, in <module>
    RanFor = pickle.load(f)
ModuleNotFoundError: No module named 'sklearn'

**Comment by VaibhavSaini19** [comment]
You can install that module yourself, it's not an error in the project
