### ISSUE TITLE
Python was not recognized 

### ISSUE THREAD

**Issue by medhun** [VaibhavSaini19/Crop-Yield-Prediction-using-ML#6]
Dashboard was running. But predict doesn't work in dahboard. It show python3 is not recognized internal or external command

**Comment by VaibhavSaini19** [comment]
Install Python and all the necessary dependencies it asks for on running the project

**Comment by medhun** [comment]
Can u sent ur number

**Comment by medhun** [comment]
Please sir

**Comment by medhun** [comment]
Helloo. Sir i can pay around 1000
