### ISSUE TITLE
Can you share some blog or detailed guide on how to setup the project that uses php and python together ?

### ISSUE THREAD

**Issue by sksinghl498** [VaibhavSaini19/Crop-Yield-Prediction-using-ML#8]

**Comment by VaibhavSaini19** [comment]
@sksinghl498 The instructions to run this project are provided in the readme file. Most programming languages come with an OS module. I have used that to invoke a python script through the command line

**Comment by sksinghl498** [comment]
@VaibhavSaini19  I know you mention in Readme . I follow all steps of readme file your website run successfully but prediction model didn't work because it shows no python module. So how to install python dependecies with php I don't know how to download python dependencies with php.

**Comment by VaibhavSaini19** [comment]
@sksinghl498 You don't use php to install python dependencies. You can install all the required dependencies through pip or conda from command prompt/terminal, just like other python packages. 
To clarify a few things, just like we run a python file from command prompt by running `python3 sample.py`, in this project we are executing a similar command through php. Php isn't directly interacting with python. It just executes that cmd, which runs the python script and produces the output to the command prompt, which is then read back by php and used in the application

**Comment by sksinghl498** [comment]
@VaibhavSaini19  I try lot but it's not work. it shows
![Screenshot from 2021-12-02 12-49-26](https://user-images.githubusercontent.com/57589135/144376155-65aefec9-10c2-4d2f-aa31-69c8f01bdfca.png)

I already installed all module in python environment .it's shows error . please help

**Comment by VaibhavSaini19** [comment]
@sksinghl498 the PHP script is calling Python 3. Did you install the required packages for Python 3?

**Comment by sksinghl498** [comment]
@VaibhavSaini19  Yes I already install python3 and python2 also.

**Comment by sksinghl498** [comment]
@VaibhavSaini19  but not run what I do next?

**Comment by VaibhavSaini19** [comment]
> @VaibhavSaini19 Yes I already install python3 and python2 also.

I wasn't talking just about installing Python 3, I was asking did you install the packages for Python 3 or did you install them for Python 2?

Try running a Python 3 from you Command Prompt and see if you can import pandas. If not, then you haven't installed things properly.

**Comment by sksinghl498** [comment]
@VaibhavSaini19  please help bro I didn't run your project. pls help !!!
